trigger:
  branches:
    include:
      - main

variables:
  - group: infra-vars-dev
  - name: imageRepository
    value: 'simple-node-ui'
  - name: dockerfilePath
    value: 'Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'
  - name: chartPath
    value: 'simple-node-ui-chart'
  - name: helmReleaseName
    value: 'simple-node-ui'

stages:
  # ------------------------
  # Build & Test Stage
  # ------------------------
- stage: Build
  displayName: 'Build and Push Image'
  jobs:
    - job: Build
      pool:
        name: abb    # custom self-hosted agent pool
      steps:
        #  Checkout the repository
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Use Node.js 18'

        #  Install, Lint, Test and Generate JUnit Report
        - script: |
            npm install
            npm run lint
            JEST_JUNIT_OUTPUT=$(Build.SourcesDirectory)/simple-node-ui/junit.xml npm test -- --coverage --reporters=default --reporters=jest-junit
          displayName: 'Install, Lint, Test'
          workingDirectory: 'simple-node-ui'

        #  Publish JUnit Results to Test Tab
        - task: PublishTestResults@2
          inputs:
            testResultsFiles: '$(Build.SourcesDirectory)/simple-node-ui/junit.xml'
            testResultsFormat: 'JUnit'
          displayName: 'Publish Test Results to ADO'

        #  Publish the junit.xml as downloadable artifact
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/simple-node-ui/junit.xml'
            ArtifactName: 'TestResults'
            publishLocation: 'Container'
          displayName: 'Publish Test Report Artifact'