apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-ui
  namespace: simple-node-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-node-ui
  template:
    metadata:
      labels:
        app: simple-node-ui
    spec:
      containers:
      - name: simple-node-ui
        image: simple-node-ui:latest  # Replace with ACR image later
        ports:
        - containerPort: 3000
        env:
        - name: APP_MESSAGE
          value: "Hello from Kubernetes"
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
